name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        numpy-version: ['1', 'dev']
        exclude:
          - python-version: '3.8'
            numpy-version: 'dev'
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ "${{ matrix.numpy-version }}" == "dev" ]]; then
            python -m pip install --pre --extra-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy;
          else
            python -m pip install 'numpy<2.0';
          fi
      - name: Run Tests
        run: |
          pytest

          # Make sure it installs
          python setup.py install
